### ISSUE TITLE
PH315-51 Fan Control works properly out of the box

### ISSUE THREAD

**Issue by mohsunb** [kphanipavan/PredatorNonSense#1]
Hello, there.

Thank you very much for this. I tried a few alternatives and only this worked on my laptop (Helios 300 2018 model). This model has no RGB lighting, so only thing I could test was the fan controls (CoolBoost, Turbo mode). It works exactly as you'd expect. I am proposing you add this model as supported to your README. But in case you don't want to bother, I can try to fork it and simplify the project, relating to my machine.

Again, thanks a lot!
Möhsün.

**Comment by mohsunb** [comment]
Okay, I decided to fork it anyway. The application has a lot of issues from a novice user's perspective. I am going to try my best to make it like a normal application and put it in AUR.

**Comment by kphanipavan** [comment]
Thank you for the feedback. Appreciate the initiative.

Also note that in newer kernel versions, `ec_sys` is no longer included in vanilla kernels, which is crucial for this program.

It has to be installed maunally, using https://github.com/FaridZelli/acpi_ec, and the program has to be pointed to the new location.

Additional insturctions and automated setup are a WIP to ease the setup.

**Comment by mohsunb** [comment]
Which versions are you referring to? I tried this on Arch Linux with kernel 5.19.13 and 6.0 is not out yet.

**Comment by kphanipavan** [comment]
File to R/W: /sys/kernel/debug/ec/ec0/io

That existed when I was on Kubuntu Focal, kernel 5.13 and 5.15

Tested the program on Fedora 35 and 36, OpenSUSE TW and Manjaro, all with latest kernels at the time (probably 5.18 and 5.19). None had the above file.

Had to use acpi_ec to fix it.

Issue regarding the same, with my comment: https://github.com/FaridZelli/ISW-Modern/issues/3

Edit: grammar and Kernel 6.0 is out, atleast on Manjaro
![image](https://user-images.githubusercontent.com/60005847/195527642-0075c5c8-a30a-4b14-aca9-9b4d9a892159.png)
