### ISSUE TITLE
qt.qpa.xcb: could not connect to display

### ISSUE THREAD

**Issue by sbstratos79** [kphanipavan/PredatorNonSense#2]
PredatorNonSense doesn't work on Hyprland. It's a wayland compositor.
I get this error:
```qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

zsh: IOT instruction (core dumped)  QT_QPA_PLATFORM=xcb pkexec python ~/git/PredatorNonSense/main.py
```
I have tried setting environment variables like `QT_QPA_PLATFORM=xcb` etc. as mentioned in the [Arch wiki](https://wiki.archlinux.org/title/Wayland#Cannot_open_display:_:0_with_Electron-based_applications). Nothing worked.

**Comment by kphanipavan** [comment]
Try the below:

1. `QT_QPA_PLATFORM="wayland;xcb"` as suggested in Arch wiki

2. cd into the folder, run `sudo python3 main.py`

**Comment by kphanipavan** [comment]
Also try 

`QT_QPA_PLATFORM="wayland"` as suggested in https://stackoverflow.com/questions/49583671/pyqt5-unable-to-find-wayland-plugin

**Comment by sbstratos79** [comment]
I am still getting the same error.

**Comment by kphanipavan** [comment]
Please provide additional info...

OS, python version, pyqt5 version, have you tried running it on any other DE or WM??

**Comment by kphanipavan** [comment]
Quick note, are you using `sudo -E` ?

```bash
export QT_QPA_PLATFORM="wayland;xcb"
sudo -E python3 main.py
```

**Comment by sbstratos79** [comment]
> Please provide additional info...
> 
> OS, python version, pyqt5 version, have you tried running it on any other DE or WM??

Some output from `QT_QPA_PLATFORM=xcb qtdiag`:
```
Qt 5.15.8 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 12.2.1 20230201) on "xcb"
OS: Arch Linux [linux version 6.2.6-arch1-1]
```
Python 3.10.10
It was working in KDE. But I don't think I tried running it in KDE Wayland.



> Quick note, are you using `sudo -E` ?
> 
> ```shell
> export QT_QPA_PLATFORM="wayland;xcb"
> sudo -E python3 main.py
> ```
I tried sudo -E as well. Didn't help. :(

**Comment by kphanipavan** [comment]
It works on KDE Plasma-Wayland on my end, so probably works for you too...
I use Manjaro BTW...

At the end, you said `didn't help`, did you get the same error or was there anything different??

Quick Q: you are running this directly on the laptop, not over SSH or other, right? have you tried running it through konsole in hyprland?

**Comment by kphanipavan** [comment]
https://wiki.archlinux.org/title/Running_GUI_applications_as_root#Using_xhost

`xhost si:localuser:root`

More refs 😅

**Comment by sbstratos79** [comment]
> https://wiki.archlinux.org/title/Running_GUI_applications_as_root#Using_xhost
> 
> `xhost si:localuser:root`
> 
> More refs sweat_smile

I was  about to install Konsole just to try out your suggestion. But the `xhost` method worked! Thanks!
Also, no I am not running it over SSH.
Btw, is this something that can be fixed on your end or not? I know running gui apps with root privileges is very tricky in wayland.

**Comment by kphanipavan** [comment]
![20230319_193813.jpg](https://user-images.githubusercontent.com/60005847/226181592-dd7a36c0-9e9f-4f50-806a-878539a9f4c4.jpg)

sudo -E works in hyprland default conf on my end as well...

**Comment by kphanipavan** [comment]
I haven't given much thought to wayland actually, I should probably test stuff there too...

I was hoping to switch from Kubuntu Focal X11 to Fedora 36, KDE, Wayland. But my experience wasn't smooth at all (nvidia hardware fgs) and I switched to Manjaro KDE X11. That was the end of my wayland saga 🫠.

For now, I will include above in the readme, have to research more for a long term solution...

Thank you for opening this issue : ]

**Comment by kphanipavan** [comment]
Also, do leave your laptop specs if you don't mind...

**Comment by sbstratos79** [comment]
Damn..

![1679235411 screensht](https://user-images.githubusercontent.com/4395586/226182218-196c421b-e40e-49d9-b9e9-db283a6620f6.png)

![image](https://user-images.githubusercontent.com/4395586/226182141-29a9e55f-a613-4971-b36e-7e9b134c4677.png)

**Comment by sbstratos79** [comment]
My experience with Wayland has been mostly neutral. Haven't encountered too many issues like this one. Most programs just work.
Although I am loving Hyprland, so far. xD
Btw, my laptop is Predator G3-572. It's getting old... I only use PredatorNonSense to change the fan speed. RBG section is useless for me.
Thanks for all the help. I will close this issue now.

**Comment by kphanipavan** [comment]
Predator G3 and the fan control works??! Interesting...

The RGB section is useless to everyone, it always has been broken lol.

Have you tried the battery limiter and GPU Overclock/Fan curve tabs?? Please report your findings at your convenience...

*My Wayland issues: (games crash on full screen, external display runs at 12fps)

**Comment by sbstratos79** [comment]
I have enabled the battery limiter. Will take some time to find if it's working.
I don't see any fan curves in the program. I was able to change the GPU overclock to Boost, but I have no way to test if it's working.

**Comment by kphanipavan** [comment]
yea so,

The GPU Boost section just changes the fan curve, i.e. the fans will run faster at a certain temperature in boost when compared to normal. It doesn't increase the GPU Power limit or add overclock, but runs the fans faster, like below...

![Screenshot_20230319_201414](https://user-images.githubusercontent.com/60005847/226183623-fe435d0d-59fe-4f21-b989-3053a7012b5c.png)

**Comment by sbstratos79** [comment]
I thought you meant the app was supposed to have a way to manually adjust the fan curve à la MSI Afterburner. But yeah, I still don't know if it really changed anything.
Oh, and for gaming, I only tried Hades and a couple of indie titles. They all worked flawlessly. Fullscreen and all. It's only been a few days since I set up wayland on my system so I haven't tried too many games.

**Comment by sbstratos79** [comment]
Battery charge limit isn't working.

**Comment by kphanipavan** [comment]
> for gaming, I only tried Hades and a couple of indie titles. They all worked flawlessly. Fullscreen and all.

Its Kwin+Wayland+Nvidia, known to break...


> Battery charge limit isn't working.

Expected, as your laptop is an older varient and may not have this feature implemented


> But yeah, I still don't know if it really changed anything. 

If you have the overclock section in your windows predator sense application, gpu boost/ fan curve works...
