### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by asp616848** [kphanipavan/PredatorNonSense#6]
sudo python3 -u "path"
Write Support Not Enabled for the EC...
Try restarting the application, Changes made to EC...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
modprobe: ERROR: could not insert 'ec_sys': Operation not permitted
Traceback (most recent call last):
  File "path", line 306, in <module>
    application = MainWindow()
                  ^^^^^^^^^^^^
  File "path", line 69, in __init__
    self.cb = True if ec_read(int(COOL_BOOST_CONTROL, 0)) == 1 else False
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path", line 32, in ec_read
    with open(EC_IO_FILE, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ec'

This error received on Predator Helios Neo 16, Mode switch button is now working but it only switches its own light and no real purpose

**Comment by kphanipavan** [comment]
Install this
https://github.com/saidsay-so/acpi_ec

It provides write access to the embedded controller, which controls the fan and other peripherals.
